from __future__ import annotations

import json
from pathlib import Path

from sku_audit.models import AuditReport, RecognitionStatus


def write_json_report(report: AuditReport, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(report.to_dict(), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def write_markdown_report(report: AuditReport, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_markdown_report(report), encoding="utf-8")


def render_markdown_report(report: AuditReport) -> str:
    summary = report.summary
    lines = [
        "# SKU Audit Report",
        "",
        f"- Report ID: `{report.report_id}`",
        f"- Input root: `{report.input_root}`",
        f"- Evidence files: `{summary.total_evidence_files}`",
        f"- Trading points: `{summary.store_count}`",
        f"- Market photo files: `{summary.market_photo_files}`",
        f"- Exact-zone files: `{summary.exact_zone_files}`",
        f"- Uncertain-zone files: `{summary.uncertain_zone_files}`",
        f"- Countable zone files: `{summary.countable_zone_files}`",
        f"- Review artifacts: `{summary.review_artifact_files}`",
        f"- Baseline recognized/brand-only observations: `{summary.recognized_observations}`",
        f"- Pending ML analysis observations: `{summary.pending_analysis_observations}`",
        f"- Needs review/retake observations: `{summary.needs_review_observations}`",
        f"- Unknown observations: `{summary.unknown_observations}`",
        "",
        "## Trading Points",
        "",
        "| Trading point | Images |",
        "| --- | ---: |",
    ]

    for store_summary in report.store_summaries:
        lines.append(f"| {store_summary.store_name} | {store_summary.image_count} |")

    lines.extend([
        "",
        "## Observations",
        "",
        "| ID | Status | Store | Zone | Confidence | Evidence | Notes |",
        "| --- | --- | --- | --- | ---: | --- | --- |",
    ])

    for observation in report.observations:
        if observation.status == RecognitionStatus.NOT_PRODUCT:
            continue
        notes = "<br>".join(observation.notes)
        store = observation.store_name or "-"
        lines.append(
            "| "
            f"`{observation.observation_id}` | "
            f"`{observation.status.value}` | "
            f"{store} | "
            f"`{observation.zone_type.value}` | "
            f"{observation.confidence:.2f} | "
            f"`{observation.source_path}` | "
            f"{notes} |"
        )

    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append(
        "This report is generated by the baseline ingestion layer. It does not yet perform real SKU recognition."
    )
    lines.append(
        "Exact-zone images are treated as candidate countable evidence; uncertain-zone images are routed to retake/manual review."
    )
    lines.append(
        "Trading point photos are marked as pending analysis until detection, OCR, visual matching, and deduplication are connected."
    )
    lines.append("")
    return "\n".join(lines)
